colors = {
    "1":"darkblue",
    "2":"orangered",
    "3":"aqua",
    "4":"aquamarine",
    "5":"azure",
    "6":"beige",
    "7":"bisque",
    "8":"black",
    "9":"blanchedalmond",
    "10":"blue",
    "11":"blueviolet",
    "12":"brown",
    "13":"burlywood",
    "14":"cadetblue",
    "15":"chartreuse",
    "16":"chocolate",
    "17":"coral",
    "18":"cornflowerblue",
    "19":"cornsilk",
    "20":"crimson",
    "21":"cyan",
    "22":"turquoise",
    "23":"darkcyan",
    "24":"darkgoldenrod",
    "25":"darkgray",
    "26":"darkgrey",
    "27":"darkgreen",
    "28":"darkkhaki",
    "29":"darkmagenta",
    "30":"darkolivegreen",
    "31":"darkorange",
    "32":"darkorchid",
    "33":"darkred",
    "34":"darksalmon",
    "35":"darkseagreen",
    "36":"darkslateblue",
    "37":"darkslategray",
    "38":"darkslategrey",
    "39":"darkturquoise",
    "40":"darkviolet",
    "41":"deeppink",
    "42":"deepskyblue",
    "43":"dimgray",
    "44":"dimgrey",
    "45":"dodgerblue",
    "46":"firebrick",
    "47":"floralwhite",
    "48":"forestgreen",
    "49":"fuchsia",
    "50":"gainsboro",
    "51":"ghostwhite",
    "52":"gold",
    "53":"goldenrod",
    "54":"gray",
    "55":"grey",
    "56":"green",
    "57":"greenyellow",
    "58":"honeydew",
    "59":"hotpink",
    "60":"indianred",
    # "1":"indigo",
    # "1":"ivory",
    # "1":"khaki",
    # "1":"lavender",
    # "1":"lavenderblush",
    # "1":"lawngreen",
    # "1":"lemonchiffon",
    # "1":"lightblue",
    # "1":"lightcoral",
    # "1":"lightcyan",
    # "1":"lightgoldenrodyellow",
    # "1":"lightgray",
    # "1":"lightgrey",
    # "1":"lightgreen",
    # "1":"lightpink",
    # "1":"lightsalmon",
    # "1":"lightseagreen",
    # "1":"lightskyblue",
    # "1":"lightslategray",
    # "1":"lightslategrey",
    # "1":"lightsteelblue",
    # "1":"lightyellow",
    # "1":"lime",
    # "1":"limegreen",
    # "1":"linen",
    # "1":"magenta",
    # "1":"maroon",
    # "1":"mediumaquamarine",
    # "1":"mediumblue",
    # "1":"mediumorchid",
    # "1":"mediumpurple",
    # "1":"mediumseagreen",
    # "1":"mediumslateblue",
    # "1":"mediumspringgreen",
    # "1":"mediumturquoise",
    # "1":"mediumvioletred",
    # "1":"midnightblue",
    # "1":"mintcream",
    # "1":"mistyrose",
    # "1":"moccasin",
    # "1":"navajowhite",
    # "1":"navy",
    # "1":"oldlace",
    # "1":"olive",
    # "1":"olivedrab",
    # "1":"orange",
    # "1":"antiquewhite",
    # "1":"orchid",
    # "1":"palegoldenrod",
    # "1":"palegreen",
    # "1":"paleturquoise",
    # "1":"palevioletred",
    # "1":"papayawhip",
    # "1":"peachpuff",
    # "1":"peru",
    # "1":"pink",
    # "1":"plum",
    # "1":"powderblue",
    # "1":"purple",
    # "1":"red",
    # "1":"rosybrown",
    # "1":"royalblue",
    # "1":"rebeccapurple",
    # "1":"saddlebrown",
    # "1":"salmon",
    # "1":"sandybrown",
    # "1":"seagreen",
    # "1":"seashell",
    # "1":"sienna",
    # "1":"silver",
    # "1":"skyblue",
    # "1":"slateblue",
    # "1":"slategray",
    # "1":"slategrey",
    # "1":"snow",
    # "1":"springgreen",
    # "1":"steelblue",
    # "1":"tan",
    # "1":"teal",
    # "1":"thistle",
    # "1":"tomato",
    # "1":"aliceblue",
    # "1":"violet",
    # "1":"wheat",
    # "1":"white",
    # "1":"whitesmoke",
    # "1":"yellow",
    # "1":"yellowgreen"
}
markers = {
    "1":"circle",
    "2":"star",
    "3":"line-ew",
    "4":"diamond",
    "5":"x-thin",
    "6":"cross",
    "7":"triangle-up",
    "8":"star",
    "9":"hourglass",
    "10":"cross-thin"
    }